# -*- coding: utf-8 -*-
"""nltk_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJs4rHCSXWNsygkpq4MC88NRVcps5gU-
"""

import nltk

nltk.download('punkt', download_dir='./nltk_data')
nltk.download('stopwords', download_dir='./nltk_data')
nltk.download('wordnet', download_dir='./nltk_data')